apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mario.serviceName }}
spec:
  type: {{ .Values.mario.type }}
  selector:
    app: mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
